# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.ssh.forward_agent = true

  config.vm.synced_folder "../", "/home/ubuntu/tailsocket"
  config.vm.provision :shell, :path => "setup.sh", privileged: false
end